### ISSUE TITLE
invalid license information

### ISSUE THREAD

**Issue by basisbit** [Esri/heatmap-layer-js#10]
The different licensing information within this repository requires some work.
The README.md and the license.txt suggest that all content of this repository is licensed under the Apache v2 license. The README.md also states `Access and Use Constraints The library is dual-licensed under the MIT and the Beerware license, feel free to use it in your projects.` but this beerware license is not explained or linked anywhere within the repo. The MIT-LICENSE.txt file details the MIT license.
So, in total this code is licensed under the following licenses, contradicting the Readme.md text:

- Apache v2
- MIT
- "Beerware"

**Comment by driskull** [comment]
Thanks @basisbit . Should be updated now
